import { Suspense } from 'react';
import type { Metadata } from 'next';
import { Ubuntu_Sans } from 'next/font/google';
import './globals.css';
import Header from './components/UI/Header';
import { Providers } from './providers';

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { BackgroundWrapper } from './components/BackgroundWrapper';

const ubuntu = Ubuntu_Sans({
  weight: ['300', '400', '500', '700'],
  variable: '--font-ubuntu',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <>
        <body className={`${ubuntu.className} relative antialiased overflow-hidden h-screen`}>
          <BackgroundWrapper/>
          <div className="absolute inset-0 z-10 flex flex-col">
            <Suspense fallback={<div>Loading...</div>}>
              <Providers>
                <div className="flex-1 overflow-y-auto">
                <Header></Header>
                  {children}
                </div>
              </Providers>
            </Suspense>
          </div>
          <ToastContainer
            position="top-center"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="dark"
          />
        </body>
      </>
    </html>
  );
}
