import { Suspense } from 'react';
import type { Metadata } from 'next';
import { Comfortaa } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { BackgroundWrapper } from './components/BackgroundWrapper';
import { NavbarDemo } from './components/UI/Navbar';
import ScrollFix from './components/ScrollFix';
import Footer from './components/UI/Footer';

const comfortaa = Comfortaa({
  weight: ['400', '500', '600', '700'],
  variable: '--font-comfortaa',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='h-full'>
      <>
        <body className={`${comfortaa.className} relative antialiased min-h-screen flex flex-col`}>
            <ScrollFix/>
            <div id='bg-root'/>
            <BackgroundWrapper/>
            <div id='app-root'>
              <Suspense>
                <Providers>
                  <NavbarDemo/>
                  <main className="flex-grow">
                    {children}
                  </main>
                  <Footer/>
                </Providers>
              </Suspense>
            </div>
          <ToastContainer
            position="top-center"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="dark"
          />
        </body>
      </>
    </html>
  );
}
